### ISSUE TITLE
[Bug] login  https://analytics.katalon.com/  captcha required

### ISSUE THREAD

**Issue by starryrbs** [katalon-studio/katalon-analytics#111]
- Katalon Studio Version:
- OS Version:
- Browser Version:

Steps to Reproduce:

1.
2.

Expected behavior: 

Screenshots:

**Comment by linhhuynhtruc** [comment]
Hi,

Captcha is required when a user enters an incorrect password for 5 consecutive times. At that time, you should log into Katalon TestOps with that account and enter the captcha. After that, you should be able to activate Katalon Studio normally.
