### ISSUE TITLE
[Feature] Colour configuration for passed status (green / blue)

### ISSUE THREAD

**Issue by aarocaes** [katalon-studio/katalon-analytics#16]
I realize that passed tests are now being shown with **blue** colour, instead of **green** as was before.

I assume this is the japanese standard, just like Jenkins, but it would be great if you could choose the colour (green or blue) for passed tests, as we have a different standard in other countries (green: ok, red: ko).

Thanks in advance.

**Comment by devalex88** [comment]
Thank you for the suggestion. Green will be used from now on.
