### ISSUE TITLE
[Feature] Katalon Analytics - Ability to add comment at test level and search

### ISSUE THREAD

**Issue by trongbui** [katalon-studio/katalon-analytics#19]
https://katalon.zendesk.com/agent/tickets/124

We usually have testing team look at each test failures to understand what caused to fail. We need to capture their investigation results for each test. So we need ability to add comment against each failed and search with comment field value when needed. Comment fields search should support for keyword search.

**Comment by huongttnguyen** [comment]
Requirement: Add a comment field on test run level. Allow user to filter by comment.

**Comment by Padoplin** [comment]
Hi @trongbui

Currently, Task in Katalon Analytics is used for keeping track of failed executions and investigations. Please refer to [Task Management](https://docs.katalon.com/katalon-analytics/docs/project-management-task.html#create-and-view-tasks) for further information.

Regards,

Padoplin
