### ISSUE TITLE
[Feature] A way to push build number and branch name

### ISSUE THREAD

**Issue by trongbui** [katalon-studio/katalon-analytics#20]
https://katalon.zendesk.com/agent/tickets/122

Katalon Analytics, shows run ID for every suite. But its hard to map and relate with SAP Ariba build number and branch that we run tests against.

Basically for each product, we have multiple branches and each branch will have build name with build number appended in it.

Lets say there is product called P1 and its has 3 branches B1, B1 and B3. Now lets say B1 branch build number is B1XXX-1000, B1XXX-1001 etc. We run automated tests against all the branches and most of the builds. Looks there is no way to pass branch and build info to Katalon Analytics currently. Can we have this looked at it?

**Comment by huongttnguyen** [comment]
KS: New attribute for user to pass custom key values on execution level. 
KA: Display key values and allow user to edit plus user should be able to filter by key value.

**Comment by huongttnguyen** [comment]
1. define global variables: 
KA_version (brand)
KA_build 
2. display on KA on test suite execution level
