### ISSUE TITLE
[Bug] Cannot connect to Katalon Analytics Server

### ISSUE THREAD

**Issue by JennerGitHub** [katalon-studio/katalon-analytics#21]
- Katalon Studio Version: 5.10.1 build 1 
- OS Version: Windows 10 
- Browser Version: Microsoft Edge

Steps to Reproduce:

1. Project Settings -> Integration -> Katalon Analytics -> Click on Enable integration , fill out form with same URL I am using from the Analytics Dashboard - provide my email password click connect and get message"Cannont connect to Katalon Analytics Server. 

https://analytics.katalon.com/team/11933/dashboard
2.

Expected behavior: Katalon Analytics connects

Screenshots:
![image](https://user-images.githubusercontent.com/28566084/51349976-fb877d80-1a74-11e9-9f6f-23aa9f76ca4a.png)

![katalonanalyticsissue2019-01-17_16-28-02](https://user-images.githubusercontent.com/28566084/51349999-0cd08a00-1a75-11e9-92d7-a259d62f6979.png)

**Comment by longngbui** [comment]
Hi @JennerGitHub,

Thank you for raising your issue to Katalon Team. After a quick look of your provided screenshots, there could be several things here.
- Change the ServerURL: https://analytics.katalon.com
- If you are behind Proxy, please config the Proxy settings in Katalon Studio first and then try to connect again. 

Let us know if it works. Thanks again for choosing Katalon!

Best,
