### ISSUE TITLE
[Feature] Integrate Profile Name into Katalon Analytics

### ISSUE THREAD

**Issue by donauerpascal** [katalon-studio/katalon-analytics#22]
We use Profiles to change between DEV and LIVE environment.

To put the profile somehow into Katalon Analytics would enable analysing the healthiness of both systems.

**Comment by kelson-pereira** [comment]
This is a good hint of improvement for Analytics!

Showing the **Profile Name** in reports makes it easy to find the test run environment.

A new column for the **Profile Name** in the **Tests Run** tab could be a good approach.

Regards,

**Comment by thongmgnguyen** [comment]
Thank you for your contribution. This feature is currently in development and will be released in a couple weeks.

**Comment by kelson-pereira** [comment]
Thank you @thongmgnguyen, it's really good to know!

Regards,

**Comment by Padoplin** [comment]
This feature is currently available in Katalon Analytics.
