### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by mgwillett** [katalon-studio/katalon-analytics#25]
- Katalon Studio Version: 5.10.1
- OS Version: Windows 10 Education
- Browser Version: Chrome 71

Steps to Reproduce:
1. Click Terminate Execution icon for test suite collection listed as Running
2. Enter execution ID to confirm and click Terminate

Expected behavior: 
Test execution should be relisted under Latest Executions but throws error instead:
/api/v1/executions/terminate?projectId=13596&order=47
Request method 'DELETE' not supported

Screenshots:
![image](https://user-images.githubusercontent.com/47605385/52732701-d5c79880-2f8e-11e9-88e0-40e4a83995db.png)

**Comment by mgwillett** [comment]
Update on this bug: Today I was able to terminate the execution shown in the screenshot without error; as expected it was moved to Latest Executions status. Code fix deployed?

**Comment by thongmgnguyen** [comment]
@mgwillett,
We released a fix version today. And it seems to be fine now.
