### ISSUE TITLE
[Feature] Allow creating multiple teams

### ISSUE THREAD

**Issue by devalex88** [katalon-studio/katalon-analytics#26]
Source: https://forum.katalon.com/t/multiple-teams/14045

> I’ve been playing around with the new analytics offering, and am greatly pleased with this addition. It may be in the works, but it would be awesome if there was the possibility of creating/managing multiple teams, to better share specific projects with specific users.

**Comment by Padoplin** [comment]
The current version of Katalon Analytics allows users to create and manage many teams and projects. Please refer to [this document](https://docs.katalon.com/katalon-analytics/docs/user-management.html#default-roles) for more information.
