### ISSUE TITLE
[Feature] Katalon Analytics - Update the Test case Name from Data set

### ISSUE THREAD

**Issue by tonythomas28** [katalon-studio/katalon-analytics#27]
Currently, we have a feature add the same test case to a test suit multiple times. 
But when we execute that test suit the report that is published in Katalon Analytics is a bit confusion

When executing a test based on a database query or Multiple Test data, the same test case is executed several times, the output generates a result with the same name of test cases for all, so it is not possible to determine which test case is the one that fails.

The question is whether it is possible to change the name of the test case at run time.
<img width="574" alt="screenshot 2019-02-18 at 2 59 44 pm" src="https://user-images.githubusercontent.com/21123857/52941012-e5c7e980-338d-11e9-9698-955a60e36a5e.png">

**Comment by Padoplin** [comment]
Hi @tonythomas28,

I'm sorry for not getting back to you earlier. Currently, Katalon Analytics does not support changing the name of a test case during run time.

Regards,
Padoplin.
