### ISSUE TITLE
[Bug] Unable to upload report in Katalon Analytics

### ISSUE THREAD

**Issue by trongbui** [katalon-studio/katalon-analytics#31]
https://katalon.zendesk.com/agent/tickets/236

After having integrated to Katalon Analytics, I am unable to upload the test reports in Katalon Analytics. I am getting an error message that: "Unable to upload report in Katalon Analytics". Kindly help.

**Comment by trongbui** [comment]
I request you to get updates from the development team, as this feature is very important for our project and it would be of great help to us. Need this urgently.

Regards, 
T Prusty

**Comment by huongttnguyen** [comment]
Attached user configuration screenshot
![issue 31](https://user-images.githubusercontent.com/47766596/53405626-d1699980-39ea-11e9-8e12-56c969a646a6.png)

**Comment by trongbui** [comment]
I am able to manually upload the reports when I log into https://analytics.katalon.com. 
I am even able to connect using my credentials in the 'Integration-->Katalon Analytics' of the project's settings. 
and I can access it when I open the reports and select Katalon Analytics-->Access Analytics. 
But not able to upload. 
Can you let me know which version are you using? 
I have already set the proxy of the tool. Do I need to ensure further settings in the tool?

**Comment by Jyotip12** [comment]
Hi team,
Any updates regarding this?

**Comment by Jyotip12** [comment]
Hi Team,

Please share the updates.

**Comment by huongttnguyen** [comment]
Hi @Jyotip12,
Can you download the latest Katalon Studio [version 6.0.6](https://www.katalon.com/) first and upload your report to KA again? 

In case the issue still persists, please click on the "Details" button and share with us the log. 
![image](https://user-images.githubusercontent.com/47766596/54247685-726c5e80-456c-11e9-8ad1-3d6159205700.png)

Thank you for your patience.

**Comment by Jyotip12** [comment]
![error_analytics](https://user-images.githubusercontent.com/47848773/54345422-09b6dc00-4669-11e9-9c51-9c0af9d78dd5.jpg)

Dear Team,

I have tried to upload the reports using the version 6.0.6, and it is not able to upload the reports. However, I am able to upload the reports automatically after the execution. But it does not show me any details such as pass, fail or even any graphs.

**Comment by Jyotip12** [comment]
![image](https://user-images.githubusercontent.com/47848773/54345931-0d972e00-466a-11e9-85f5-04369c191018.png)

Please find the screenshot of the summary of the reports, that get automatically uploaded after execution.

**Comment by huongttnguyen** [comment]
Hi @Jyotip12,

Can you go to Help > Error Log and send us your log file. 
<img width="354" alt="Screen Shot 2019-03-14 at 4 33 38 PM" src="https://user-images.githubusercontent.com/47766596/54346382-82bd3000-4677-11e9-89c1-b4ef197d7995.png">

If there is no personal data you can post the log file here, otherwise, please send to info@katalon.com .

Thank you for your patience. 

Regards,

**Comment by Jyotip12** [comment]
[log.log](https://github.com/katalon-studio/katalon-analytics/files/2965769/log.log)
Dear Team,

Please find the logs.

**Comment by thongmgnguyen** [comment]
@Jyotip12,
It seems like your network is using self-certificate SSL, please check with your IT for the valid SSL. For more information:
[https://jfrog.com/knowledge-base/how-to-resolve-unable-to-find-valid-certification-path-to-requested-target-error/]()

**Comment by Jyotip12** [comment]
Hi Team,
Please let me know the below details regarding points related to SSL certificate generation:
1. How to generate Request file(csr file) for this application i.e Katalon Studio tool
2. what format of certificate? a) .cer b) .pfx which includes private key c) .pem ?
