### ISSUE TITLE
[Feature] View Image in the UI and not by downloading

### ISSUE THREAD

**Issue by sundarciet** [katalon-studio/katalon-analytics#34]
Team,

when i run a test case, i am capturing a image after the success or failure. We need an option to view the uploaded images in the UI rather than downloading. This gives a better and quick clarity to end user or business user to look into the failure test case

**Comment by Padoplin** [comment]
Hi @sundarciet 

I'm glad to let you know that you can soon directly view screenshots in Katalon Analytics in the upcoming version. Stay tuned! 

Padoplin.
