### ISSUE TITLE
[Bug] Unable to delete results

### ISSUE THREAD

**Issue by Mowogman** [katalon-studio/katalon-analytics#36]
Katalon AnalyticsBETA 0.17.0. Copyright © 2019 Katalon LLC

- Browser Version: Chrome

Steps to Reproduce:

1. Opened Katalon Analytics 
2. I have tried to delete some unwanted results the results will not delete  

Expected behavior: The results should delete

Screenshots:

**Comment by huongttnguyen** [comment]
Hi @Mowogman,
Sorry for a late response on this. Did you mean that you were unable to delete execution? 
Can you please try again and let us know if it still happens? 

Regards, 
Huong

**Comment by Mowogman** [comment]
It still fails randomly to delete executions. A bulk delete would be a nice feature.

[cid:image001.png@01D4D4AA.AD8B3FA0]

Ian Fraser
Senior Automation Specialist

Tatts Group Limited
87 Ipswich Rd Woolloongabba Qld 4102

M +61 413 698 372      E Ian.Fraser@tattsgroup.com<mailto:Ian.Fraser@tattsgroup.com>
tattsgroup.com<http://www.tattsgroup.com/>


[cid:4F2A434D-DFE0-4326-A759-6A62801CED72]

**Comment by huongttnguyen** [comment]
Hi @Mowogman, 
Can you try again with the latest Katalon Analytics 0.18.0 to see if you can delete the result? Also, thank you for your feature request regarding bulk delete, we've put them in our backlog for consideration.

**Comment by junktest7** [comment]
Katalon Analytic Team - I am unable to delete test executions. When I attempt to type in the delete modal, only NaN displays.

NOTE: Before I found this page, I commented in the Community Bug Reports section.

![Katalon_delete_execution](https://user-images.githubusercontent.com/48928186/56050078-c8652b00-5cff-11e9-83a0-676adeba806c.PNG)

**Comment by Mowogman** [comment]
The Delete process still has random failures and at times its very slow to delete.

**Comment by Mowogman** [comment]
![image](https://user-images.githubusercontent.com/43425487/56101295-c6040a80-5f65-11e9-9bbe-7b3ac47f3cfd.png)

**Comment by glenandrewthomson** [comment]
I'm also getting this problem. The server returns 500 for example when I send a delete request to:
https://analytics.katalon.com/api/v1/executions?projectId=22724&order=73

**Comment by Mowogman** [comment]
What happened to the bulk delete suggestion?

**Comment by Padoplin** [comment]
Hi @Mowogman,

We've already put "bulk delete" in our backlog, in the meantime stay tuned. 

Padoplin
