### ISSUE TITLE
[Bug]For every run, there are 2 entries in Katalon Analytics Dashboard

### ISSUE THREAD

**Issue by siddharthkolli** [katalon-studio/katalon-analytics#46]
- Katalon Studio Version:6.0.5
- OS Version:Windows 7 64bit
- Browser Version:Chrome 72.0.3626.121

Steps to Reproduce:

1. Once I have established a connection with my Katalon Analytics board, there are 2 records being created for one single run. 

Expected behavior: 
There should be only 1 record for every run. 

Screenshots:

![image](https://user-images.githubusercontent.com/45843372/54359055-d2a3f300-4687-11e9-907b-2e3fe65617f9.png)

**Comment by huongttnguyen** [comment]
Hi @siddharthkolli,
Just to let you know that this issue has been resolved in the latest Katalon Studio v6.1.0. Thank you for reporting. 

Kind regards, 
Mia

**Comment by siddharthkolli** [comment]
Thank you for fixing it in real quick time.

-Siddharth.

**Comment by huongttnguyen** [comment]
Is it working fine now on your side?

**Comment by siddharthkolli** [comment]
Yes, it is working fine.

Thanks,
Siddharth.
