### ISSUE TITLE
[Bug] JUnit reports uploaded from Command Line show empty fields

### ISSUE THREAD

**Issue by kelson-pereira** [katalon-studio/katalon-analytics#49]
- Katalon Report Uploader Version: 0.0.3
- OS Version: MacOS

**Steps to Reproduce:**

1. Create a report in JUnit format;

2. Import the report into Katalon Analytics with the command line below;

```
    java -jar katalon-report-uploader-0.0.3.jar \
    --kit.server.api=http://analytics.katalon.com \
    --projectId=xxxx \
    --path="/tmp/junit.xml" \
    --email=kelson.xxxxxx.com \
    --password=xxxxxx \
    --type=junit
```

**Expected behavior:** 
When I import a JUnit report into Katalon Analytics, the fields identified in the screenshot (orange rectangle) should be displayed. I believe that as of version 0.18.0, the fields are no longer being displayed. The Status Passed field is also not correct and in this case it has failed.

**Screenshots:**
![Captura de Tela 2019-03-26 às 22 23 56](https://user-images.githubusercontent.com/47066976/55043906-016e8180-5017-11e9-8652-2ed249b4d0b1.png)

**Comment by huongttnguyen** [comment]
Hi @kelson-pereira, 
Thank you for reporting. We've received your feedback and will resolve it in the next release. Sorry for any inconvenience this might have caused.

**Comment by kelson-pereira** [comment]
Hi @huongttnguyen,
Thank you for your quick response. The functionality of importing JUnit reports into KA is very important. If you have any questions about this case, please contact me. Regards

**Comment by kms-loantran** [comment]
Hi @kelson-pereira,
I've just verified your issue in the production as following: java -jar katalon-report-uploader-0.0.5.jar --projectId=xxxxx --email=xxxxx --password=xxxxx  --type=junit --path=/Users/loantran/Documents/sample-junit/casperjs.xml 
and the result displays correctly:
<img width="1410" alt="Screen Shot 2019-08-15 at 3 45 12 PM" src="https://user-images.githubusercontent.com/29113513/63087356-3060a200-bf7c-11e9-92b4-dd21ae0a5fd2.png">

Can you try again with katalon-report-uploader-0.0.5.jar? If you still meet the issue, send us your .xml file for further investigation
