### ISSUE TITLE
Results are not attached 

### ISSUE THREAD

**Issue by juagonza** [katalon-studio/katalon-analytics#51]
The executions are uploaded but the results for each execution are not saved, so it seems like the execution is empty and without testcases, even though when the test suite is executed the tool in real time displays the cases in process.  This happens using the CLI and the GUI
- Katalon Studio Version:  6.1.1
- OS Version: Ubuntu 18.04.2 / Windows 10
- Browser Version: Web Services

Steps to Reproduce:
![bug](https://user-images.githubusercontent.com/49498781/55914019-52e44800-5ba3-11e9-956d-60496e0c604e.PNG)

1. Execute a test suite 
2. Wait to see the results on the tool

Expected behavior: 
The execution contains the test cases results and information

Screenshots:

**Comment by hhajni** [comment]
I ran into the same issue. 
The results were visible though 6-7 hours later... I'd prefer to see them right away 😊

**Comment by junktest7** [comment]
This is currently happening for me as well. When I attempt to manually upload an existing test execution.

**Comment by easolorzanog** [comment]
Hi,
Me too, the results for each execution are not saved. It stopped working

![Katalon Analytics](https://user-images.githubusercontent.com/35602643/56061411-ba36ff00-5d3f-11e9-95de-a8c521c8ba5d.png)

**Comment by junktest7** [comment]
I read somewhere else that the results ARE displaying, however only after a certain amount of time, or something like that. I assume that they are aware of this and are working on a fix.

ALSO NOTE: After I delete the non responsive test executions, the test execution IDs do not update accordingly. Which means the deleted executions ARE being stored somewhere. Where is that and can users access this archived section?

**Comment by easolorzanog** [comment]
hi junktest7, 

Yes, you right!, the results are visible today, 18 hours later... i hope that fix soon.

thanks

**Comment by dhavalgit** [comment]
I feel the same issue, Can anybody from katalon-analytics team please confirm what is going on?

**Comment by thongmgnguyen** [comment]
We currently have performance issue with large size log. In order to keep the server safe, we have to reduce the concurrent parsing data thread. So it take a while to handle result. We will release a fix version in a couple days.

**Comment by dlopes690** [comment]
Hey @thongmgnguyen ,
Is there an update for when this issue will be resolved?

**Comment by thongmgnguyen** [comment]
Hi all,
We released a fixed version yesterday.
