### ISSUE TITLE
[Bug] Unable to Invite Users

### ISSUE THREAD

**Issue by Mowogman** [katalon-studio/katalon-analytics#53]
![image](https://user-images.githubusercontent.com/43425487/56103890-67945780-5f78-11e9-87cc-19331f4f45c7.png)

- Katalon Studio Version: Katalon Analytics 
- OS Version: Windows 10
- Browser Version: Chrome

Steps to Reproduce:

1. I am trying to invite new users to Analytics  
2. When the they attempt to accept the invitation they get an error see screen print attached 

Expected behavior: Users can join

Screenshots: Attached at top

**Comment by quidl** [comment]
Some reasons for the error
- The email you use to invite and email that the new user uses to login when clicking on the invitation email is different
- The invitation link has been used
- New users receive some invitation emails and they clicked on one of them => Other invitation emails will be invalid. The error will occur when they continue to click on another invitation email

Could you double check again?

**Comment by Mowogman** [comment]
It would be nice if you  added some comments when you close a bug

**Comment by Padoplin** [comment]
Hi @Mowogman,

I'm sorry for any inconvenience this may have caused. Our developer has already replied to you since April and we haven't received any feedback since then; hence we think your issues have already been solved. 

Padoplin
