### ISSUE TITLE
Upload existing report is not populating data acurately

### ISSUE THREAD

**Issue by junktest7** [katalon-studio/katalon-analytics#54]
- Katalon Studio Version: 6.1.0
- OS Version: Win 10
- Browser Version: Chrome

Steps to Reproduce:

1. Locate existing test suite execution and open.
2. Use the Katalon Analytics -> Upload option
3. Review what is updated to Katalon Analytics

Expected behavior: 
 3a. Example: 'Started' header should be renamed 'Uploaded' (for manual/existing uploads) or create a new column
 3b. Example: Test Suite, Profile, & Duration all blank (should populate with info)
 3c. Example: Total, Passed, Failed, Error, Incomplete are all displaying 0 (should populate with info)
 3d. Example: Test data is not displaying at time of upload. Taking a long time or 1 day wait time. (results should display after upload and not after a long time)

Screenshots:

![Katalon_upload](https://user-images.githubusercontent.com/48928186/56160884-22265900-5f7d-11e9-9a38-ba891001a08a.PNG)

**Comment by LuisEscamillaMartin** [comment]
Hi:

I have the same problem.

Regards.
![KatalonAnalytics](https://user-images.githubusercontent.com/7894148/56561000-3cc48780-65a6-11e9-9466-d11f3be8e539.png)

**Comment by thongmgnguyen** [comment]
Hi,
We faced a performance issue last week. A fixed version was deployed yesterday.
