### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by dipakkumardas** [katalon-studio/katalon-analytics#56]
- Katalon Studio Version:
- OS Version:
- Browser Version:

Steps to Reproduce:

1.
2.

![Blank](https://user-images.githubusercontent.com/38430510/57289095-5dc5c600-70d8-11e9-8036-8514c28cfe7c.jpg)

Expected behavior: 

Screenshots:

**Comment by dipakkumardas** [comment]
On Katalon analytices

**Comment by Padoplin** [comment]
Hi @dipakkumardas,

When your results are being parsed, the name field should be blank.

Regards,

Padoplin
