### ISSUE TITLE
[Bug] "status" needs to be replaced with "statuses" on "Test Cases" tab

### ISSUE THREAD

**Issue by abergquist** [katalon-studio/katalon-analytics#58]
On the "Test Cases" tab, "status" needs to be replaced with "statuses" in the following sentence:

"All status retrieved from the most recent execution of each Test Cases."

- **Katalon Studio Version:** Katalon Analytics BETA (web page)
- **OS Version:** Windows 7
- **Browser Version:** Google Chrome - Version 74.0.3729.131 (Official Build) (64-bit)

**Steps to Reproduce:**

1. Go to https://analytics.katalon.com/
2. Log in
3. Go to "Test Cases" tab

**Expected behavior:** 

I expect the sentence to read as follows:

"All statuses retrieved from the most recent execution of each Test Cases."

Screenshots:
![image](https://user-images.githubusercontent.com/7118508/57890116-91e16b00-77eb-11e9-91ba-078847982a8f.png)

**Comment by Padoplin** [comment]
Hi @abergquist,

Thank you for your feedback, the UI of the newly launched version of Katalon Analytics has been significantly changed. Your suggested page is no longer available.

Padoplin
