### ISSUE TITLE
[Feature] The number of Test Executions per day, link to failed test

### ISSUE THREAD

**Issue by pgkanaris** [katalon-studio/katalon-analytics#59]
a.	We need the ability to see the number of test executed by date. Quality Assurance best practices track the number test executed during a test cycle. We build trends based on our throughput over time not by test suite or collection.
b.	In a collection we need to know which test suite has the failures. If we do not know which test suite we are required to click on the included test suites until we find the failed test.
c.	Can we have a link on failed test which will open all of the failed test in the collection/suite?

**Comment by pgkanaris** [comment]
Hi Padoplin,

Could you tell me the disposition of the issue and if a feature when the feature is planned for implementation?
Thank you,
Paul

**Comment by Padoplin** [comment]
Hi @pgkanaris,

I'm glad to let you know that a and b are available now in the current version of Katalon Analytics while your c idea is about to be released in the upcoming version of Katalon Analytics.

Here are some instructions for b and c: 
b. To view which test suite has failures, navigate to Test Maintenance > all test suites of that project displays with their number of failed executions.
c. In terms of opening all failed executions of a Test Suite/Test Suite Collection, also navigate to Test Maintenance, you just need to add a simple filter "status=failed", then you will have a picture of failed executions in that TS/TSC.

Thank you for your efforts to make Katalon Analytics a better tool. Happy testing!

Padoplin

**Comment by pgkanaris** [comment]
Hi Padoplin,

I saw the latest release and had some questions for you.

  1.  Where can we see a user guide on what the features do and how best to use them?
  2.  I looked at the execution report and the results seem off by a lot for our project. See attached report
  3.  Can filters be added to the reports such as date, status, collection name, profile?

Please let me know if you have any questions and also where best I can post issues either through our support or other methods.

Thank you,
Paul

[cid:image002.jpg@01D35C50.A4971460]
Paul Kanaris QA Architect
305 Church at North Hills Street Suite 350 | Raleigh, NC | 27609
[cid:image003.png@01D202CC.25A9E1C0]
D: 984-255-2021 | M: 919-519-2754
At Netsmart<http://www.ntst.com/>, We Believe EveryDay<http://everydaymatters.com/>Matters<http://everydaymatters.com/>®

**Comment by Padoplin** [comment]
Hi @pgkanaris 

Thank you for reaching me. Here are replies to your concerns.

1. Please navigate to [Katalon Analytics (Beta) Documents](https://docs.katalon.com/katalon-analytics/docs/overview.html) to explore features offered by Katalon Analytics (Beta).
2. I can't see your attachment. Please kindly attach again what you want me to see.
3. In the current version of Katalon Analytics, merely the Performance report in the Executions Tab can be filtered by multiple fields while the other reports in Reports Tab are able to be filtered by status and customized time period.

If you still have any concerns, feel free to contact me.

Regards,

Padoplin

**Comment by pgkanaris** [comment]
Hello Padoplin,

I tried to send you the documents a word document. Not sure if the email system removed the file. I am going to place the attachment content below:
[A screenshot of a computer  Description automatically generated]
Shows the test collection runs. The 65 test cases are in a collection of 8 test suites.
[A screenshot of a social media post  Description automatically generated]
Based on the results yesterday should have shown about 10 runs executed but shows only 2 passed and 1 failed.
[A screenshot of a social media post  Description automatically generated]
As for the number of test cases executed, we may want to see just the number of unique test cases (Status pass fail is helpful), but also told instances of test cases.

Please let me know if you still have any issues seeing the content.

Thank you,
Paul


[cid:image002.jpg@01D35C50.A4971460]
Paul Kanaris QA Architect
305 Church at North Hills Street Suite 350 | Raleigh, NC | 27609
[cid:image003.png@01D202CC.25A9E1C0]
D: 984-255-2021 | M: 919-519-2754
At Netsmart<http://www.ntst.com/>, We Believe EveryDay<http://everydaymatters.com/>Matters<http://everydaymatters.com/>®

**Comment by Padoplin** [comment]
Hola @pgkanaris,

Please send the attachments to info@katalon.com for further investigation. 

Thanks, Paul.

Jass

**Comment by pgkanaris** [comment]
You are welcome. I look forward to working with the analytics next. We have made great progress on the Katalon Studio implementation and are now moving into the reporting stage.

Please let me know the process of issue notification and suggestion/enhancement request process for Katalon Analytics. For studio, we use our support account to enter the items.

Thank you,
Paul


[cid:image002.jpg@01D35C50.A4971460]
Paul Kanaris QA Architect
305 Church at North Hills Street Suite 350 | Raleigh, NC | 27609
[cid:image003.png@01D202CC.25A9E1C0]
D: 984-255-2021 | M: 919-519-2754
At Netsmart<http://www.ntst.com/>, We Believe EveryDay<http://everydaymatters.com/>Matters<http://everydaymatters.com/>®

**Comment by Padoplin** [comment]
Hi @pgkanaris,

I'm writing to let you know that there is a bug in the number of Test Executions per day report and we're fixing it at the moment. Thank you for your contribution. 

In terms of issue notifications and enhancement requests for Katalon Analytics, please continue using this repo as the main channel.

Once again, thanks a lot. Feel free to contact me for any issue with Katalon Analytics.

Regards,

Padoplin

**Comment by pgkanaris** [comment]
Thank you, I look forward to the fix.


[cid:image002.jpg@01D35C50.A4971460]
Paul Kanaris QA Architect
305 Church at North Hills Street Suite 350 | Raleigh, NC | 27609
[cid:image003.png@01D202CC.25A9E1C0]
D: 984-255-2021 | M: 919-519-2754
At Netsmart<http://www.ntst.com/>, We Believe EveryDay<http://everydaymatters.com/>Matters<http://everydaymatters.com/>®

**Comment by pgkanaris** [comment]
Hi Padoplin,

Do you have an estimated fix date on the execution count? My was tracking the test run graph for executions but that is no longer present. I.e. the graph that showed the results by Execution ID. Will the old graph showing the run results by execution ID be available in the future?

Thank you
Paul


[cid:image002.jpg@01D35C50.A4971460]
Paul Kanaris QA Architect
305 Church at North Hills Street Suite 350 | Raleigh, NC | 27609
[cid:image003.png@01D202CC.25A9E1C0]
D: 984-255-2021 | M: 919-519-2754
At Netsmart<http://www.ntst.com/>, We Believe EveryDay<http://everydaymatters.com/>Matters<http://everydaymatters.com/>®

**Comment by Padoplin** [comment]
Hello @pgkanaris,

We expect to fix this bug within 2-4 weeks. I'm sorry but could you please elaborate on your question regarding the old graph?

Padoplin
