### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by slrongji** [katalon-studio/katalon-analytics#60]
- Katalon Studio Version: docker image tried 6.1.5 and also 5.10.1
- OS Version: Linux 64bit
- Browser Version:

Steps to Reproduce:

 Since 2 days ago, Have no idea is it related  but what might affect is that I create another new team (previously it works fine, but I do have only one team at that time.)
 Now  when I am testing and which upload result to one of my teams, certain project, during the test, all the counter looks correct. (please see the fist screenshot) but after the console shows the reports are uploaded to analytics (please see the fist screenshot3) , then all counters for tests are shown 0 and it only shows passed in analytics (please see the fist screenshot2) 

Expected behavior: 

Screenshots:
![counting was correct](https://user-images.githubusercontent.com/20752413/58719030-0f51d180-83cf-11e9-9017-4f73e88f2d53.PNG)
![image](https://user-images.githubusercontent.com/20752413/58719035-14168580-83cf-11e9-830c-4ae87778fe22.png)
![image](https://user-images.githubusercontent.com/20752413/58719318-99019f00-83cf-11e9-8d16-61d14ed5bd21.png)

**Comment by slrongji** [comment]
Now I am getting
	[CIRCULAR REFERENCE:com.kms.katalon.integration.analytics.exceptions.AnalyticsApiExeception: {"timestamp":1559319461678,"status":500,"error":"Internal Server Error","exception":"java.lang.IllegalStateException","message":"An internal error occurred. Please contact your system administrator.","path":"/api/v1/katalon-test-reports"}]

**Comment by thongmgnguyen** [comment]
Hi @slrongji,
Could you have a look again? Are your results correct now ?
