### ISSUE TITLE
[Bug] Report not getting generated in Katalon Analytics. In status column it shows the busy symbol.

### ISSUE THREAD

**Issue by rahulbasu86** [katalon-studio/katalon-analytics#61]
Report not getting generated in Katalon Analytics. In status column it shows the busy symbol.

- Katalon Studio Version: 6.1.4
- OS Version: Linix/MAC
- Browser Version: Chrome/Firefox

![image](https://user-images.githubusercontent.com/42985211/58806003-37198300-85e3-11e9-9924-d3538bfb2eda.png)

**Comment by thongmgnguyen** [comment]
Hi @rahulbasu86,
I checked in database,  your results are parsed successfully. Could you please review them again?
