### ISSUE TITLE
[Feature] Filter test results by status

### ISSUE THREAD

**Issue by daniel-wilkinson** [katalon-studio/katalon-analytics#7]
When searching through test case results in Katalon Analytics, it would be helpful to be able to filter on each of the headings, particularly status. i.e. I can then filter on tests that have passed or tests that have failed.

![](https://user-images.githubusercontent.com/43000524/49885308-cad97600-fe2e-11e8-9c84-275aa7e30468.png)

**Comment by devalex88** [comment]
Thank you for the suggestion. This feature has been available since 0.17.0.

Please be noted that statuses are only set for test cases executed afterward.
