### ISSUE TITLE
[Bug]  Now after upload the reports, it will always only show till the first fail or error testcase, but actually there are more

### ISSUE THREAD

**Issue by slrongji** [katalon-studio/katalon-analytics#70]
Since today
Steps to Reproduce:

1. running testsuit within docker image, with analytics integration, which will upload afterwards
2. during running the counter was increased properly
3. after upload, the number is now always shown testcases till the first fail or error testcase , I got one project always shows 18 testcases with the last one failed, but actually there are more than 70 shown during the running, and my next project always shows 8 with the last one error, and actually during running it shows more than 40 test cases
![Capture](https://user-images.githubusercontent.com/20752413/61857563-b8471500-aec4-11e9-8231-c1f7dfa7e43e.PNG)
![image](https://user-images.githubusercontent.com/20752413/61857684-e3316900-aec4-11e9-8967-f0fa3eba30f2.png)
![Capture2](https://user-images.githubusercontent.com/20752413/61857975-7a96bc00-aec5-11e9-99ae-f4f846b7c5d8.PNG)
![Capture3](https://user-images.githubusercontent.com/20752413/61857985-7cf91600-aec5-11e9-86de-9531f4d424bb.PNG)

**Comment by thongmgnguyen** [comment]
Could you give me your screenshot and KS version, as well as your katalon account?

**Comment by slrongji** [comment]
inside docker the katalon version is 6.1.5
and everything starts from yesterday.  now for the new uploaded one you can not delete also. this morning you event can not see the uploaded results.
