### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by arielvillalobosf** [katalon-studio/katalon-analytics#74]
- Katalon Studio Version:  katalon Analitycs Beta
- OS Version: Windows 10 
- Browser Version: Chrome 

Steps to Reproduce: 

1. Go to Executions
2. Scroll to Executions List.
3.Select Delete (over anyone)
4.  Modal :  This Execution (1) will be deleted permanently.  ??    
5. Press DELETE. 
6.  The execution is not cleared. 
 
Expected behavior:   The execution must be cleared from the list. 

Screenshots:

**Comment by Padoplin** [comment]
Hello @arielvillalobosf,

Once you have successfully deleted the execution, it may take a little while for it to disappear from the test executions table due to the async pattern. 

Regards,

Padoplin

**Comment by arielvillalobosf** [comment]
Thank you @Padoplin!!

Have a nice day!
