### ISSUE TITLE
[Bug] Unable to Invite New User Using Invitation Link

### ISSUE THREAD

**Issue by jtolotta** [katalon-studio/katalon-analytics#78]
- Katalon Studio Version: Katalon Analytics
- OS Version: Windows 10
- Browser Version: Chrome

Steps to Reproduce:

- Invite new users to Analytics
- Invited user follows link in email
- Error is displayed and user has no permissions to access organization

Expected behavior: Users can join the orgnization

Screenshots:
![2019-09-12 12_04_14-Invitation Accepted - Katalon Analytics](https://user-images.githubusercontent.com/11189424/64749646-dcf35c80-d505-11e9-97c4-4965e40426ff.png)

**Comment by jtolotta** [comment]
I have attempted to invite the person 3 times resulting in the same error.

**Comment by Padoplin** [comment]
Hi @jtolotta,

Please make sure that person has already logged in to his/her account before clicking that link or that error will be thrown.

Regards,

Padoplin

**Comment by jtolotta** [comment]
To: @Padoplin 

Thanks for the quick response.
The user already has an existing Katalon account is currently logged into Katalon Analytics.
Tried again and the error still occurs.
Currently when logged into Katalon Analytics, they have access to their own organization, teams and projects.

**Comment by jtolotta** [comment]
This issue was resolved with the following steps.

1. Created a new user invitation
1. User received the email invite
1. User copied the invitation link
1. Navigated using Microsoft Edge web browser to the invitation URL
1. Redirect to the Katalon Analytics login page
1. User logged into Katalon Analytics
1. User accepted to organization
