### ISSUE TITLE
[Feature] Supplying an API key replaces the By Name on the reports view

### ISSUE THREAD

**Issue by somedumbfox** [katalon-studio/katalon-analytics#81]
When an analytics api key is provided in CLI, the By "author" is replaced with the name of the license key provided, IE: By "AzureDevOps". This will help in identifying if the test suite was fired via automation, or manually by a user.
![Capture](https://user-images.githubusercontent.com/22248602/65603585-f075dd00-df73-11e9-9b2e-17f4af7b93ca.PNG)
![Capture2](https://user-images.githubusercontent.com/22248602/65603590-f23fa080-df73-11e9-8545-b584e75ad4b8.PNG)

**Comment by Padoplin** [comment]
Hi Juan Lopez,

Thank you for your suggestion. I think there may be some misunderstanding here. API Keys are used for replacing your account password and do not indicate the way in which test results have been uploaded.

Automatically uploading test results means you turn it on in project settings and Katalon Studio does the job while manually uploading test results means you press the Access Analytics button any time you want to upload a result in the result tab. [By+ Username] is understood to tell your team which account has uploaded the results but it says nothing about via automation or manual way.

I hope it helps.

Cheers,

Jass

**Comment by somedumbfox** [comment]
I understand. I guess I didn't word my request right. We're trying out the software to see if it's a good solution for us. However it's noted that since we'll be using Azure to automatically run tests when changes are made, we would like a way that would allow us to know that the test was fired by Azure and not by a personal account.

Aside from having to make an additional account and sharing that login (which is not a best practice), another method would be nice, and less wasteful. Also something that would allows us to store in a KeyVault and use as a variable for CLI use.

**Comment by Padoplin** [comment]
Hi @somedumbfox 

We will consider putting this request in our backlog. Since we have many tickets from users in the queue, it might take time.

Kind regards,

Jass.
