### ISSUE TITLE
[Feature]Ability to upload Test Suite Collections

### ISSUE THREAD

**Issue by pgkanaris** [katalon-studio/katalon-analytics#83]
We need the ability to upload test collection results from Katalon. On occasion team members have failed to turn on automatic upload after debugging issues and the test collection run is lost.

Thank you,

**Comment by Padoplin** [comment]
Dear Paul,

We have already put this in our product backlog. Thank you for your suggestion.

Jass

**Comment by devalex88** [comment]
This feature has been implemented in Katalon Studio 7.0.0.
