### ISSUE TITLE
It's possible to include multiple releases at a time at Katalon Analytics

### ISSUE THREAD

**Issue by JecksonVictor** [katalon-studio/katalon-analytics#84]
Katalon Analytics
- Katalon Studio Version: 7.0.0
- OS Version: Windows 10 64b
- Browser Version: Opera Browser 63.0.3368.88

Steps to Reproduce:
1. I create a Team in Katalon Analytics
2. I add a project to this Team
3. I go to the realeases pages of this project
4. I click in the Create Realease button
5. I fill in the Name field
6. I fill in the Description field
7. I rapidly click on the Create button
8. Then I see the same release was created multiple times.

Expected behavior: 
The Create button should not operate the same action more than once.

Screenshots:
![Screenshot_8](https://user-images.githubusercontent.com/22164320/65916082-1869a400-e3ab-11e9-8931-a4bd8b2b60e9.png)

**Comment by Padoplin** [comment]
Hi @JecksonVictor 

Thank you for informing us, we will fix this bug in the upcoming releases. 

Cheers

Jass

**Comment by devalex88** [comment]
This bug has been fixed.
