### ISSUE TITLE
[Bug] - I cannot click on button Create Offline License

### ISSUE THREAD

**Issue by thaophan24** [katalon-studio/katalon-analytics#88]
- Katalon Studio Version: 7.0.8
- OS Version:
- Browser Version:

Steps to Reproduce:

1. Log in to Katalon TestOps
2. Go to Organization -> License -> Katalon Studio Enterprise
3. Click Create Offline License

Expected behavior: I can click Create Offline License and insert a Machine ID

Screenshots:

**Comment by Padoplin** [comment]
Hello Thao

If you are using trial licenses, unfortunately, you're not allowed to create offline licenses. Read more about Katalon License [here](https://docs.katalon.com/katalon-studio/docs/license.html#katalon-studio-license-types).

Padoplin

**Comment by devalex88** [comment]
To create offline licenses, please subscribe to Katalon Studio Enterprise yearly plan.
