### ISSUE TITLE
No Connection to katalon analitycs 

### ISSUE THREAD

**Issue by Zhann02** [katalon-studio/katalon-analytics#89]
- Katalon Studio Version: 19
- OS Version: Windows 10
- Browser Version: ..

Steps to Reproduce:

1.open katalon studio
2.open project
3.Settings – Integration – Katalon Analytics Give details and connect 
On this steep the project no connect with katalon analitycs the proccess is loading alltimes

Expected behavior: 

Screenshots:

**Comment by devalex88** [comment]
Hi, please help ask this question in https://forum.katalon.com since this list is for tracking bugs and features only.
